# -*- coding: utf-8 -*-
"""Another copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWLAAMWfdzBo0DMdRNFSSTSZI3AQEyLY
"""

x= 10
if x>5:
  print("x is greater than 5")
  print(x)



x = 7
if x>10:
    print("x is greater than 10")
else:
    print(" x is lesser than 10")

for i in range (0,10):
  print(i)

fruits=["Mango","banana","kiwi"]
for x in fruits:
  print(x)

class employee:
  x= "name"
e1=employee
print(e1.x)

import pandas as pd
data={
    "calories":[457,143,354],
    "duration":[56,12,42],
    "intensity":["low","high","medium"]
    }
df=pd.DataFrame(data)
print(df)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/titanic.csv")
df.head(10)

df.describe()

df.info()

df.columns

df.loc[df['Age']<10]

df.rename(columns={"Age":"age", "Ticket":"Ticket rate"}).head()

df.drop(labels=["PassengerId"],axis=1,inplace=True)
df.columns

df.isnull().sum()

import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic.head()

g=sns.FacetGrid(titanic,col="class")
g.map(sns.histplot,"age")

sns.heatmap(titanic.corr(),annot=True,cmap="coolwarm")

sns.pointplot(x="class",y="fare",hue="alive",data=titanic)

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.datasets import load_iris

iris=load_iris()
data=iris.data
target=iris.target
print(target)
feature=iris.feature_names
print(feature)

plt.figure(figsize=(8,6))
plt.scatter(data[:,0],data[:,1],c=target,cmap='Blues',edgecolors='red')
plt.show()

plt.figure(figsize=(8,6))
plt.hist([data[target==0,2],data[target==1,2],data[target==2,2]],bins=4,color=['skyblue','lightgreen','coral'],alpha=1)
plt.title("sepal length vs sepal width")
plt.xlabel('Sepal length')
plt.ylabel('Sepal width')
plt.legend()
plt.show()

import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day2_Session3_Dataset1.csv')
data.head(10)

editable_csv=data.to_csv('new_sample.csv')


gthy5jw6uw6ju6o8[]

data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day2_Session3_Dataset1.csv')
data.head(10)

from matplotlib import pyplot as plt
_df_1['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='CustomerID', y='Age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

new_data = data.drop(['CustomerID'], axis=1)
new_data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
sns.heatmap(new_data.corr(),annot=True,cmap='rainbow')

g=sns.FacetGrid(new_data,col='Genre')
g.map(sns.barplot,x=new_data['Age'],y=new_data['Spending_Score'])



g=sns.FacetGrid(new_data,col='Genre')
g.map(sns.boxplot,x=new_data['Age'],y=new_data['Spending_Score'])

import matplotlib as plt
g=sns.FacetGrid(new_data,col='Genre')
g.map(sns.bubbleplot,x=new_data['Age'],y=new_data['Spending_Score'])

import seaborn as sns
new_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day2_Session3_Dataset1.csv')

g = sns.FacetGrid(new_data, col="Genre")
g.map(sns.scatterplot, x="Age", y="Spending_Score")
plt.show()

g=sns.FacetGrid(new_data,col='Genre')
g.map(sns.scatterplot,x=new_data['Age'],y=new_data['Spending_Score'])

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# st.write ('# Streamlit Calculator')
# First_Number=st.number_input('First Number')
# Second_Number=st.number_input('Second Number')
# Third_Number=First_Number*Second_Number
# st.write('# Answer is ', Third_Number)

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

!pip install streamlit -q
!streamlit run
import streamlit as st
st.title("Mini Project")
option=st.sidebar.selectbox('Select a page:',('Page 1','Page 2'))
if option=='Page 1':
  st.write('content in this page')
elif option=='Page 2':
  st.write('This is the content in second page')
st.sidebar.markdown("!!!-----!!!")
import streamlit as st

st.sidebar.write("Made with streamlit")

import streamlit as st
st.title('Hello everyone')

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile My_application.py

!wget -q -O - ipv4.icanhazip.com

!streamlit run My_application.py & npx localtunnel --port 8501